quarkus.http.port=8081

kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}


mp.messaging.incoming.encomendas.connector=smallrye-kafka
mp.messaging.incoming.encomendas.topic=encomendas.recebidas
mp.messaging.incoming.encomendas.group.id=notificacao-encomendas
mp.messaging.incoming.encomendas.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.encomendas.auto.offset.reset=earliest

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:postgresql://localhost:5433/sistemaencomendas}

quarkus.hibernate-orm.schema-management.strategy=update

quarkus.log.level=INFO

# E-mail
# true: simula o envio e mostra o conteúdo no log
# false: envia pelo Gmail usando as variáveis abaixo
quarkus.mailer.mock=${MAILER_MOCK:false}

quarkus.mailer.from=${GMAIL_USUARIO:portaria@exemplo.com}
quarkus.mailer.host=smtp.gmail.com
quarkus.mailer.port=587
quarkus.mailer.username=${GMAIL_USUARIO:}
quarkus.mailer.password=${GMAIL_SENHA_APP:}
quarkus.mailer.tls=false
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.login=REQUIRED
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN

quarkus.log.category."io.quarkus.mailer".level=DEBUG
quarkus.log.category."io.vertx.ext.mail".level=DEBUG
