quarkus.http.port=8081

kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.encomendas.connector=smallrye-kafka
mp.messaging.incoming.encomendas.topic=encomendas.recebidas
mp.messaging.incoming.encomendas.group.id=notificacao-encomendas
mp.messaging.incoming.encomendas.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.encomendas.auto.offset.reset=earliest

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/sistemaencomendas

quarkus.hibernate-orm.schema-management.strategy=update

quarkus.log.level=INFO

quarkus.mailer.mock=true
