quarkus.http.port=8081

kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.encomendas.connector=smallrye-kafka
mp.messaging.incoming.encomendas.topic=encomendas.recebidas
mp.messaging.incoming.encomendas.group.id=notificacao-encomendas
mp.messaging.incoming.encomendas.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.encomendas.auto.offset.reset=earliest

quarkus.log.level=INFO

quarkus.mailer.mock=true
